
# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.heap_4=y

# BEGIN AUTO-ADDED BY MCUXPRESSO EXTENSION 06/04/2026 13:50
CONFIG_MCUX_COMPONENT_driver.edma_soc=y
CONFIG_MCUX_COMPONENT_CMSIS_Driver_Include.USART=y
CONFIG_MCUX_COMPONENT_device.RTE=y
CONFIG_MCUX_COMPONENT_driver.ctimer=y
CONFIG_MCUX_COMPONENT_driver.edma4=y
CONFIG_MCUX_COMPONENT_driver.lpflexcomm_lpuart_edma=y
CONFIG_MCUX_COMPONENT_driver.lptmr=y
CONFIG_MCUX_COMPONENT_driver.cmsis_lpuart=y
# END AUTO-ADDED BY MCUXPRESSO EXTENSION
