
# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.heap_4=y

# BEGIN AUTO-ADDED BY MCUXPRESSO EXTENSION 09/04/2026 03:46
CONFIG_MCUX_COMPONENT_driver.edma_soc=y
CONFIG_MCUX_COMPONENT_CMSIS_Driver_Include.SPI=y
CONFIG_MCUX_COMPONENT_device.RTE=y
CONFIG_MCUX_COMPONENT_driver.edma4=y
CONFIG_MCUX_COMPONENT_driver.lpflexcomm_lpspi=y
CONFIG_MCUX_COMPONENT_driver.lpflexcomm_lpspi_edma=y
CONFIG_MCUX_COMPONENT_driver.cmsis_lpspi=y
# END AUTO-ADDED BY MCUXPRESSO EXTENSION

# BEGIN AUTO-ADDED BY MCUXPRESSO EXTENSION 12/04/2026 22:28
CONFIG_configTICK_RATE_HZ=1000
# END AUTO-ADDED BY MCUXPRESSO EXTENSION

# BEGIN AUTO-ADDED BY MCUXPRESSO EXTENSION 12/04/2026 23:37
CONFIG_configTOTAL_HEAP_SIZE=14240
# END AUTO-ADDED BY MCUXPRESSO EXTENSION
